apiVersion: v1
kind: Namespace
metadata:
  name: physio-web
  labels:
    name: physio-web
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: physio-web
  name: physio-web
  labels:
    app: physio-web
spec:
  selector:
    matchLabels:
      app: physio-web
  template:
    metadata:
      labels:
        app: physio-web
    spec:
      hostNetwork: true
      containers:
        - name: physio-web
          image: saichler/physio-web:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate
